image:
    node:8.15.0

stages:
    - installation
    - build

installing-dependencies:
    stage: installation
    tags: 
        - docker
    script:
        - npm install -g expo-cli
        - npm install
        - echo "Managed to install correctly"

build-job:
    stage: build
    tags: 
        - docker
    script:
        - npm install -g expo-cli
        - npm install
        - echo $PWD
        - cd nhs_mobile
        - echo $PWD
        - expo start
        - echo "Built project successfully"
