image:
    node:14.0.0

stages:
    - prebuild
    - deploy

prebuild-job:
    stage: prebuild
    tags: 
        - docker
    script:
        - npm install -g expo-cli
        - cd nhs_mobile
        - npm install
        - expo login -u keivan.s10@gmail.com -p Test1234
        - expo prebuilt
        - echo "Built project successfully"

deploy-job:
    stage: deploy
    tags:
        - docker
    script:
        - npm install -g expo-cli
        - cd nhs_mobile
        - npm install
        - expo login -u keivan.s10@gmail.com -p Test1234
        - expo publish
        - echo "Published project successfully"
